My user icon
peno022/fjord-books_app pull request #4
Opened 2022-06-25 16:12 UTC by mayumonj

## 課題URL
https://bootcamp.fjord.jp/practices/146

レビューよろしくお願いいたします。

2022-06-30 00:56 UTC, u1tnk requested changes
ほぼ問題無いのですが関係の無い修正が入っているようです。
業務ではNGなので修正お願いします 🙏

2022-06-30 00:56 UTC, u1tnk commented on Gemfile
> +gem 'kaminari'
kaminariは関係無いと思います。

2022-07-02 03:46 UTC, mayumonj commented on Gemfile
> +gem 'kaminari'
@u1tnk 
レビューありがとうございます！
修正しない状態だと、下記のRubocopのエラーになったため、エラー解消のために修正を入れていました。。
```
Gemfile:65:1: C: [Correctable] Bundler/OrderedGems: Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem devise should appear before kaminari.
gem 'devise'
```
たしかに今回のプラクティス要件には関係ないので修正前の状態に戻そうと思いますが、元のファイルを修正いただくよう依頼したほうがよいでしょうか？
もしくは、そもそもこのエラーが出るのが私だけでしょうか？

2022-07-02 08:12 UTC, mayumonj commented
レビューいただきありがとうございました！
ご指摘対応したのですが、コメントの内容質問したく、ご確認いただけると幸いです🙇‍♀️

2022-07-02 16:11 UTC, u1tnk commented on Gemfile
> +gem 'kaminari'
あー、なるほど。
と聞いて試してみました。最初は出なかったのですが、最新にしたところ同様に発生しました！rubocopのバージョンアップで変わってしまったんじゃないかと思います。
私の方で元プラクティスにはPR出しておこうと思いますが、もしPRの練習したいのであれば @mayumonj さんが出しても良いですがどうしましょう？

プラクティスに話を戻すと、そういうときはPRにコメントしておくとスムーズだったと思います 💪 
本プラクティスではそのrubocopのエラーは無視する事として大丈夫です 🙆‍♀️

2022-07-02 16:11 UTC, u1tnk approved these changes

2022-07-04 13:31 UTC, mayumonj commented on Gemfile
> +gem 'kaminari'
@u1tnk 
> プラクティスに話を戻すと、そういうときはPRにコメントしておくとスムーズだったと思います 💪

こちらおっしゃるとおりです。すみませんでした。

PR出すのやってみます！
元プラクティスの`06-user_icon` `07-follow_users` `08-comments` の3つのブランチに対して同じ修正のPRを出せばよいでしょうか？

2022-07-05 03:16 UTC, u1tnk commented on Gemfile
> +gem 'kaminari'
ああ、3つ影響するブランチがあるんですね。とりあえず一つ( `06-user_icon`)に向けて作って、そのPRの中で影響するブランチも指摘しておけば良いと思います。取り込み側の方でそれぞれのブランチに反映すれば良いので。

2022-09-05 15:14 UTC, merged